name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          PRERELEASE: ${{ github.event.release.prerelease }}
          DEFAULT_BRANCH: ${{ github.event.release.target_commitish == github.event.repository.default_branch }}
        run: | 
          echo "PRERELEASE=$PRERELEASE"
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH"
