name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          PRERELEASE: ${{ github.event.release.prerelease }}
          DRAFT: ${{ github.event.release.draft }}
          DEFAULT_BRANCH: ${{ github.event.release.target_commitish == github.event.repository.default_branch }}
        run: |                
          echo "PRERELEASE=$PRERELEASE"
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH"
          echo "DRAFT=$DRAFT"
          latest_tag=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          if [[ "${latest_tag}" == "${{ github.event.release.tag_name }}" ]]; then
            echo "This is the latest release."
